#ifndef _KEYDEFINE_H
#define _KEYDEFINE_H

enum{
_NO_KEY = 0,				/*0*/
_HP_ON_KEY,   				/*1*/
_HP_OFF_KEY,				/*2*/
_DIGI_KEY,					/*3*/

_PANEL_POWER_KEY, 		/*4*/
_PANEL_HD_RADIO_KEY, 		/*5*/
_PANEL_AM_FM_KEY, 		/*6*/
_PANEL_PRESET_UP_KEY, 	/*7*/
_PANEL_PRESET_DN_KEY, 	/*8*/
_PANEL_ARROW_UP_KEY, 	/*9*/
_PANEL_ARROW_DOWN_KEY, 	/*10*/
_PANEL_ARROW_LEFT_KEY, 	/*11*/
_PANEL_ARROW_RIGHT_KEY, 	/*12*/
_PANEL_ENTER_KEY,  		/*13*/
_PANEL_INPUT1_KEY,		/*14*/
_PANEL_INPUT2_KEY,		/*15*/
_PANEL_INPUT3_KEY,		/*16*/
_PANEL_INPUT4_KEY,		/*17*/
_PANEL_INPUT5_KEY,		/*18*/
_PANEL_INPUT6_KEY,		/*19*/
_PANEL_INPUT7_KEY,		/*20*/
_PANEL_INPUT8_KEY,		/*21*/
_PANEL_PLIIX_KEY,			/*22*/
_PANEL_7CH1_INPUT_KEY,	/*23*/
_PANEL_HDMI1_KEY,			/*24*/
_PANEL_HDMI2_KEY,			/*25*/
_PANEL_ENCODER_PLUS_KEY,	/*26*/
_PANEL_ENCODER_MINUS_KEY,/*27*/

_REMOTE_POWER_ON_KEY,	/*28*/
_REMOTE_POWER_OFF_KEY,	/*29*/
_REMOTE_AM_KEY,			/*30*/
_REMOTE_FM_KEY,			/*31*/
_REMOTE_TUNER_SCAN_KEY,	/*32*/
_REMOTE_MEMORY_KEY,		/*33*/
_REMOTE_TUNER_SEEK_UP_KEY,	   /*34*/
_REMOTE_TUNER_SEEK_DOWN_KEY, /*35*/
_REMOTE_DIGI_0_KEY,			   /*36*/
_REMOTE_DIGI_1_KEY,			   /*37*/
_REMOTE_DIGI_2_KEY,			   /*38*/
_REMOTE_DIGI_3_KEY,			   /*39*/
_REMOTE_DIGI_4_KEY,			   /*40*/
_REMOTE_DIGI_5_KEY,			   /*41*/
_REMOTE_DIGI_6_KEY,			   /*42*/
_REMOTE_DIGI_7_KEY,			   /*43*/
_REMOTE_DIGI_8_KEY,			   /*44*/
_REMOTE_DIGI_9_KEY,			   /*45*/
_REMOTE_TEN_PLUS_KEY,		   /*46*/
_REMOTE_FM_MODE_KEY,			   /*47*/
_REMOTE_SETUP_KEY,			   /*48*/
_REMOTE_BRIGHT_KEY,			   /*49*/
_REMOTE_TEST_KEY,				   /*50*/
_REMOTE_LATE_KEY,				   /*51*/
_REMOTE_ARROW_UP_KEY,		   /*52*/
_REMOTE_ARROW_DOWN_KEY,	   /*53*/
_REMOTE_ARROW_LEFT_KEY,		   /*54*/
_REMOTE_ARROW_RIGHT_KEY,	   /*55*/
_REMOTE_ENTER_KEY,			   /*56*/
_REMOTE_MUTE_KEY,				   /*57*/
_REMOTE_VOLUME_UP_KEY,		   /*58*/
_REMOTE_VOLUME_DOWN_KEY,	   /*59*/
_REMOTE_PLIIX_KEY,				   /*60*/
_REMOTE_SUR_MODE_KEY,		   /*61*/
_REMOTE_NEO96_24_KEY,		   /*62*/
_REMOTE_CES7_1_KEY,			   /*63*/
_REMOTE_SEEK_KEY,				   /*64*/
_REMOTE_INPUT1_KEY,			   /*65*/
_REMOTE_INPUT2_KEY,			   /*66*/
_REMOTE_INPUT3_KEY,			   /*67*/
_REMOTE_INPUT4_KEY,			   /*68*/
_REMOTE_INPUT5_KEY,			   /*69*/
_REMOTE_INPUT6_KEY,			   /*70*/
_REMOTE_INPUT7_KEY,			   /*71*/
_REMOTE_INPUT8_KEY,			   /*72*/
_REMOTE_7CH1_IN_KEY,			   /*73*/
_REMOTE_EQ_KEY,				   /*74*/
_REMOTE_HD_AM_KEY,			   /*75*/
_REMOTE_HD_FM_KEY,			   /*76*/
_REMOTE_TXT_DISPLAY_KEY,		   /*77*/
_REMOTE_HDMI1_KEY,			   /*78*/
_REMOTE_HDMI2_KEY,			   /*79*/

_REMOTE_Z2_POWER_ON_KEY,	/*80*/
_REMOTE_Z2_POWER_OFF_KEY,	/*81*/
_REMOTE_Z2_AM_KEY,			/*82*/
_REMOTE_Z2_FM_KEY,			/*83*/
_REMOTE_Z2_PRESET_UP_KEY,	/*84*/
_REMOTE_Z2_PRESET_DOWN_KEY,/*85*/
_REMOTE_Z2_MUTE_KEY,			/*86*/
_REMOTE_Z2_VOLUME_UP_KEY,	/*87*/
_REMOTE_Z2_VOLUME_DOWN_KEY,/*88*/
_REMOTE_Z2_INPUT1_KEY,		/*89*/
_REMOTE_Z2_INPUT2_KEY,		/*90*/
_REMOTE_Z2_INPUT3_KEY,		/*91*/
_REMOTE_Z2_INPUT4_KEY,		/*92*/
_REMOTE_Z2_INPUT5_KEY,		/*93*/
_REMOTE_Z2_INPUT6_KEY,		/*94*/
_REMOTE_Z2_INPUT7_KEY,		/*95*/
_REMOTE_Z2_INPUT8_KEY,		/*96*/
_REMOTE_Z2_7CH1_IN_KEY,		/*97*/
_REMOTE_Z2_HD_AM_KEY,		/*98*/
_REMOTE_Z2_HD_FM_KEY,		/*99*/
_REMOTE_Z2_HDMI1_KEY,		/*100*/
_REMOTE_Z2_HDMI2_KEY,		/*101*/

_NAME_UP_KEY,					/*102*/
_NAME_DOWN_KEY,				/*103*/
_NAME_LEFT_KEY,				/*104*/
_NAME_RIGHT_KEY,				/*105*/
_NAME_ENTER_KEY,				/*106*/

_PANEL_SUR_MODE_KEY, 			/*107*/
_PANEL_NEO6_KEY,          			/*108*/
_PANEL_CES7_1_KEY,			/*109*/
_PANEL_UPDATE_KEY,			/*110*/

_PANEL_add_0,					/*111*/
_PANEL_add_1,					/*112*/
_PANEL_add_2,					/*113*/
_PANEL_add_3,					/*114*/
_PANEL_add_4,					/*115*/

_PANEL_HDMI3_KEY,			/*24*/
_PANEL_HDMI4_KEY,			/*25*/
_PANEL_RADIO_KEY,			/*24*/
_PANEL_TVSOUND_KEY,			/*25*/
_REMOTE_HDMI3_KEY,			   /*78*/
_REMOTE_HDMI4_KEY,			   /*79*/
_REMOTE_TVSOUND_KEY,			   /*79*/
_REMOTE_LP_MEMORY1_KEY,        /*0X43*/
_REMOTE_LP_MEMORY2_KEY,        /*0X44*/
_REMOTE_RADIO_CHANNEL_ADD_KEY,        /*0X45*/
_REMOTE_RADIO_CHANNEL_RED_KEY,        /*0X46*/
};
#endif

